version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: biblioteca_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 2s
      retries: 10

  app:
    build: .
    container_name: micronaut-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
        mysql:
          condition: service_healthy
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: biblioteca_db
      DB_USER: biblioteca_user
      DB_PASSWORD: biblioteca_pass
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
